### ISSUE TITLE
[UPDATE] ProjectData에 카테고리 값 추가 요청

### ISSUE THREAD

**Issue by rdg1029** [DefCon-Apps/DefCon-BE#31]
# Description
```typescript
export interface ProjectData{
    title: String,
    content: String,
    date: String,
    description: String,
    image: Array<String>,
    tech: Array<String>,
    user: Array<ProjectMemberData>,
//  category: "android" | "web" | "repair" | String (예시)
}
```

프로젝트 데이터에 카테고리 값을 추가하면 좋을 것 같습니다.
만약 추가 되면 프론트에서 프로젝트 리스트를 보여줄 때 아래 사진처럼 분류해서 보여 줄 예정입니다.
~~시간 있을 때 천천히 하십쇼~~

<img width="415" alt="Screen Shot 2023-01-08 at 4 41 25 PM" src="https://user-images.githubusercontent.com/10252712/211185660-20b8338b-a3ab-4b91-b198-a11c95e219c1.png">

**Comment by yymin1022** [comment]
확인이요!
